controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\AvisClientsController::index

    
client_dashboard:
    path: /client/page
    controller: App\Controller\ClientPageController::index


admin_dashboard:
    path: /admin/page
    controller: App\Controller\AdminPageController::index

homepage:
    path: /
    controller: App\Controller\HomepageController::index
